# Jekyll Configuration for GitHub Pages
# Enable clean URLs without .html extension

# Site settings
title: "Coastline Spray Foam Solutions"
description: "Professional spray foam insulation contractor serving Florida"
url: "https://coastlinesprayfoamsolutions.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Clean URLs - remove .html extension
permalink: /:title/

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: /:basename/

# Exclude files from processing
exclude:
  - README.md
  - TESTING.md
  - deploy.md
  - Code Citations.md
  - sprayfoam.code-workspace
  - node_modules/
  - vendor/

# Include files
include:
  - _pages

# SEO and social
author: "Coastline Spray Foam Solutions"
twitter:
  username: coastlinesprayfoam
facebook:
  app_id: 
  publisher: 
social:
  name: "Coastline Spray Foam Solutions"
  links:
    - https://coastlinesprayfoamsolutions.com

# Analytics
google_analytics: 

# Compression
sass:
  style: compressed

# Security
safe: true
