# Cloudflare Pages Configuration for Static Website
name = "coastlinesprayfoam"
# Updated to force Pages to pick up a new build (ISO date)
compatibility_date = "2025-08-16"

# Static assets configuration
[assets]
directory = "astro-website/dist"